steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/searce-academy/imran-flaskapp', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/searce-academy/imran-flaskapp']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cicd-demo', '--image', 'gcr.io/searce-academy/imran-flaskapp', '--region', 'us-central1']
images:
- gcr.io/searce-academy/imran-flaskapp
